# Generated by Django 4.2.11 on 2024-04-28 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poste',
            name='id',
            field=models.CharField(max_length=100000000000, primary_key=True, serialize=False),
        ),
    ]
